= Salesforce Webhook Ingestor


== How to build with OpenShift
----
oc new-build java:openjdk-11-el7~https://gitlab.com/rhi-demo/salesforce-webhook-ingestor.git
----

optionally, you may use incremental builds to make your future builds faster:

----
oc patch bc/salesforce-webhook-ingestor -p '{"spec":{ "strategy":{ "sourceStrategy":{ "incremental": true } } }}'
----


== Required environment variables

[options="header"]
|=======================
| Variable | Example Value                                      | Definition
| SF_CLIENT_ID | 31345254523huiunexabyxvaxajijiaxaex | The Connected App Consumer Key
| SF_CLIENT_SECRET | 31345254523huiunexabyxvaxajijiaxaex | The Connected App Consumer Secret
| SF_USERNAME | user@email.com | user used to log in the Salesforce instance
| SF_PASSWORD | passswordToken |  Salesforce instance user's password + security token
| SF_INSTANCE | https://example-dev-ed.my.salesforce.com |  Your Dev instance created
| AB_JOLOKIA_OFF | true | Jolokia doesn't work with Quarkus
|=======================

== Create a secret for Salesforce credentials

----
oc create secret generic salesforce-secret --from-literal=SF_CLIENT_ID= --from-literal=SF_CLIENT_SECRET= --from-literal=SF_USERNAME= --from-literal=SF_PASSWORD= --from-literal=SF_INSTANCE=
----

== Salesforce Configuration

To work with Salesforce you need to apply some configurations first. Here are the steps needed to connect to Salesforce successfully.

=== Create a Connected App

In order to authenticate the application, an application must be created in Salesforce. Go to *Setup -> App Manager -> New Connected App* to create the new Application.
Once you have it you will have access to the *SF_CLIENT_ID* and *SF_CLIENT_SECRET*.

=== Permite users to self-authorize

After creating the the connected app you need to allow self-authorization for this app. Go to *Setup -> Apps -> Connected Apps -> Managed Connected Apps -> edit your app*. Set the *Permitted Users* to *All user may self-authorize*.

=== Create an Apex Trigger

An Apex Trigger will generate a webhook to the 3scale endpoint every time an Opportunity is altered. To do so, go to *Setup -> Object Manger -> Opportunity -> Triggers -> New*. You may use the following as a template:

----
Trigger rhi_demo_opportunity on Opportunity (after insert,after update,after delete,after undelete) {

    String url = '3scale Product url + user_key';

    String content = Webhook.jsonContent(Trigger.new, Trigger.old);

    Webhook.callout(url, content);

}
----

=== Add the URL to Remote Site Settings

You need to allow the Apex Trigger to access the 3scale endpoint. To do that access: *Setup -> Remote Site Settings -> New Remote Site*.
