apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salesforce-webhook-ingestor
  namespace: openshift-gitops
spec:
  destination:
    namespace: integration
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://gitlab.com/rhi-demo/salesforce-webhook-ingestor.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
