kind: Deployment
apiVersion: apps/v1
metadata:
  name: salesforce-webhook-ingestor
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"asana-adapter"}]'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://gitlab.com/rhi-demo/salesforce-webhook-ingestor.git'
  labels:
    app: salesforce-webhook-ingestor
    demo: rhi-demo
    app.kubernetes.io/component: salesforce-webhook-ingestor
    app.kubernetes.io/instance: salesforce-webhook-ingestor
    app.kubernetes.io/name: salesforce-webhook-ingestor
    app.kubernetes.io/part-of: salesforce-webhook-ingestor
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-version: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesforce-webhook-ingestor
  template:
    metadata:
      labels:
        app: salesforce-webhook-ingestor
        demo: rhi-demo
        deploymentconfig: salesforce-webhook-ingestor
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          terminationMessagePath: /dev/termination-log
          name: salesforce-webhook-ingestor
          env:
            - name: AB_JOLOKIA_OFF
              value: 'true'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 15020
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: salesforce-secret
          image: quay.io/gcamposo/salesforce-webhook-ingestor:1.0.5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 20
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
