apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesforce-webhook-ingestor
    demo: rhi-demo
  name: salesforce-webhook-ingestor
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
  - port: 15020
    protocol: TCP
    name: monitoring
    targetPort: 15020
  selector:
    app: salesforce-webhook-ingestor
